### ISSUE TITLE
查询客户 编辑项 可能存在问题

### ISSUE THREAD

**Issue by GitCHQL** [codingXiaxw/CustomerManagement#13]
编辑后无论男女都显示 女。
可能问题如下：edt.jsp 32行

 <input type="radio" name="gender" value="male" id="male" <c:if test="${customer.gender eq 'male'}"/>checked="checked"/>
                <label for="male">男</label>
                <input type="radio" name="gender" value="female" id="female" <c:if test="${customer.gender eq 'female'}"/> checked="checked"/>
                <label for="female">女</label>
改为
 <input type="radio" name="gender" value="male" id="male" <c:if test="${customer.gender eq 'male'}">checked="checked"</c:if>/>
                <label for="male">男</label>
                <input type="radio" name="gender" value="female" id="female" <c:if test="${customer.gender eq 'female'}">checked="checked"</c:if> />
                <label for="female">女</label>
后正常，
谷歌浏览器 ，win764位。

**Comment by codingXiaxw** [comment]
老哥可以麻烦你在github上提个pr吗？我merge一下




| |
13476191847
邮箱：13476191847@163.com
|

签名由 网易邮箱大师 定制

在2018年02月13日 18:25，LEI QIAO 写道：

编辑后无论男女都显示 女。
可能问题如下：edt.jsp 32行

<input type="radio" name="gender" value="male" id="male" <c:if test="${customer.gender eq 'male'}"/>checked="checked"/>
男
<input type="radio" name="gender" value="female" id="female" <c:if test="${customer.gender eq 'female'}"/> checked="checked"/>
女
改为
<input type="radio" name="gender" value="male" id="male" <c:if test="${customer.gender eq 'male'}">checked="checked"</c:if>/>
男
<input type="radio" name="gender" value="female" id="female" <c:if test="${customer.gender eq 'female'}">checked="checked"</c:if> />
女
后正常，
谷歌浏览器 ，win764位。
